version: '3.8'

services:
  voice-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GRADIO_SERVER_NAME=0.0.0.0
      - DECODER_CONFIG_NAME=firefly_gan_vq
      - COMPILE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/app/models
      - ./cache:/app/cache
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./references:/app/references
    restart: unless-stopped 