version: '3.8'

x-common-settings: &common-settings
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  ulimits:
    memlock: -1
    stack: 67108864
  shm_size: '2gb'
  security_opt:
    - no-new-privileges:true
  read_only: true
  tmpfs:
    - /tmp:exec,mode=777
  cap_drop:
    - ALL
  depends_on:
    redis:
      condition: service_healthy
  init: true
  dns:
    - 8.8.8.8
    - 8.8.4.4
  stop_grace_period: 30s

services:
  video-generator:
    build:
      context: .
      dockerfile: services/video_generator/Dockerfile
    volumes:
      - ./models:/app/models:ro
      - ./shared:/app/shared:ro
    <<: *common-settings
    environment:
      - SKIP_MODEL_DOWNLOAD=true
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_HOME=/usr/local/cuda
      - TORCH_CUDA_ARCH_LIST=8.6
      - XFORMERS_ENABLE_FLASH_ATTENTION=true
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    runtime: nvidia
    depends_on:
      redis:
        condition: service_healthy
      models:
        condition: service_completed_successfully

  image-generator:
    <<: *common-settings
    build:
      context: .
      dockerfile: services/image_generator/Dockerfile
    volumes:
      - ./models:/app/models:ro
      - ./shared:/app/shared:ro
    environment:
      - SKIP_MODEL_DOWNLOAD=true
      - NVIDIA_VISIBLE_DEVICES=1
      - CUDA_VISIBLE_DEVICES=1
    ports:
      - "8002:8000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    runtime: nvidia

  text-generation:
    <<: *common-settings
    build:
      context: .
      dockerfile: services/text_generation/Dockerfile
    volumes:
      - ./models:/app/models:ro
      - ./shared:/app/shared:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
      - CUDA_VISIBLE_DEVICES=2
    ports:
      - "8003:9000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    runtime: nvidia

  voice-generator:
    <<: *common-settings
    build:
      context: .
      dockerfile: services/voice_generator/Dockerfile
    volumes:
      - ./models:/app/models:ro
      - ./shared:/app/shared:ro
    environment:
      - SKIP_MODEL_DOWNLOAD=true
      - NVIDIA_VISIBLE_DEVICES=3
      - CUDA_VISIBLE_DEVICES=3
    ports:
      - "8004:9000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    runtime: nvidia

  video-editor:
    <<: *common-settings
    build:
      context: .
      dockerfile: services/video_editor/Dockerfile
    volumes:
      - ./models:/app/models:ro
      - ./shared:/app/shared:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=4
      - CUDA_VISIBLE_DEVICES=4
      - SKIP_MODEL_DOWNLOAD=true
    ports:
      - "8005:8000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    runtime: nvidia

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    sysctls:
      - vm.overcommit_memory=1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis_data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
  ai-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24

dashboard:
  <<: *common-settings
  build:
    context: .
    dockerfile: services/dashboard/Dockerfile
  ports:
    - "8000:8000"
  environment:
    - API_HOST=0.0.0.0
    - API_PORT=8000
  depends_on:
    - video-generator
    - image-generator
    - text-generation
    - voice-generator
    - video-editor

models:
  build:
    context: .
    dockerfile: Dockerfile.models
  volumes:
    - ./models:/app/models
  command: ["bash", "download_models.sh"] 