apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  # O valor abaixo é a codificação em base64 de "PROD_API_TOKEN_ABC123" (por exemplo)
  apiToken: UFJPRF9BUFBJX1RPS0VOX0FCQzEyMw==