apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: content-api-cluster
spec:
  api:
    port: 6443
    k0sApiPort: 9443
    externalAddress: api.ruanpiscitelli.com
  storage:
    type: etcd
  network:
    provider: calico
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  telemetry:
    enabled: false
  extensions:
    helm:
      repositories:
      - name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
      charts:
      - name: prometheus
        chartname: prometheus-community/prometheus
        version: "15.5.3"
        namespace: monitoring
        values: |
          server:
            persistentVolume:
              size: 50Gi
      - name: nginx-ingress
        chartname: ingress-nginx/ingress-nginx
        version: "4.7.1"
        namespace: ingress-nginx
  images:
    default_pull_policy: IfNotPresent
    calico:
      cni:
        image: calico/cni
        version: v3.24.1
      node:
        image: calico/node
        version: v3.24.1
    coredns:
      image: coredns/coredns
      version: 1.9.3
    metrics_server:
      image: registry.k8s.io/metrics-server/metrics-server
      version: v0.6.3
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
  features:
    metrics:
      enabled: true
    gpu:
      enabled: true
    rbac:
      enabled: true 