# k0s - Configuração do Serviço de Geração de Texto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generator
  namespace: content-api
  labels:
    app: text-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-generator
  template:
    metadata:
      labels:
        app: text-generator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: text-generator
        image: text-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "4"
          requests:
            memory: "8Gi"
            cpu: "2"
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: text-gen-api-key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-password
        - name: VLLM_ENDPOINT
          value: "http://vllm-service:8000/generate"
        volumeMounts:
        - name: models-cache
          mountPath: /app/models
        - name: shared-cache
          mountPath: /app/cache
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: models-cache
        persistentVolumeClaim:
          claimName: models-pvc
      - name: shared-cache
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: text-generator-service
  namespace: content-api
spec:
  selector:
    app: text-generator
  ports:
  - port: 8000
    targetPort: http
    name: http
  - port: 8001
    targetPort: metrics
    name: metrics
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: text-generator-hpa
  namespace: content-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-generator
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# Configuração do Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: content-api
  labels:
    name: content-api 