# k0s - Configuração de Cache com etcd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: content-api
data:
  cache.yaml: |
    type: etcd
    endpoints:
      - http://etcd-cache-service:2379
    prefixes:
      text: "content-api/text/"
      image: "content-api/image/"
      voice: "content-api/voice/"
      video: "content-api/video/"
      video-edit: "content-api/video-edit/"
    ttl: 3600
    max_retries: 3
    retry_interval: 1.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-cache
  namespace: content-api
  labels:
    app: etcd-cache
spec:
  replicas: 3  # Aumentado para alta disponibilidade
  selector:
    matchLabels:
      app: etcd-cache
  template:
    metadata:
      labels:
        app: etcd-cache
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2379"
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.0
        command:
        - etcd
        - --name=$(POD_NAME)
        - --initial-advertise-peer-urls=http://$(POD_IP):2380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(POD_IP):2379
        - --initial-cluster-token=content-api-etcd
        - --initial-cluster=$(INITIAL_CLUSTER)
        - --initial-cluster-state=new
        - --data-dir=/var/lib/etcd
        - --auto-compaction-retention=1
        - --snapshot-count=10000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INITIAL_CLUSTER
          value: "etcd-0=http://etcd-0.etcd-cache:2380,etcd-1=http://etcd-1.etcd-cache:2380,etcd-2=http://etcd-2.etcd-cache:2380"
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl endpoint health
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl endpoint health
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-data-claim

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cache-service
  namespace: content-api
spec:
  selector:
    app: etcd-cache
  ports:
  - port: 2379
    targetPort: client
    name: client
  - port: 2380
    targetPort: peer
    name: peer
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cache
  namespace: content-api
spec:
  clusterIP: None
  selector:
    app: etcd-cache
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data-claim
  namespace: content-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Aumentado para suportar todos os serviços 