# k0s - Configuração do Serviço de Geração de Vídeo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generator
  namespace: content-api
  labels:
    app: video-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-generator
  template:
    metadata:
      labels:
        app: video-generator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: video-generator
        image: video-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "32Gi"
            cpu: "8"
          requests:
            memory: "16Gi"
            cpu: "4"
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: video-gen-api-key
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: secret-key
        - name: ETCD_ENDPOINT
          value: "http://etcd-cache-service:2379"
        - name: CACHE_PREFIX
          value: "content-api/video/"
        volumeMounts:
        - name: models-cache
          mountPath: /app/models
        - name: shared-cache
          mountPath: /app/cache
        - name: cache-config
          mountPath: /app/config/cache
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: models-cache
        persistentVolumeClaim:
          claimName: models-pvc
      - name: shared-cache
        emptyDir: {}
      - name: cache-config
        configMap:
          name: cache-config

---
apiVersion: v1
kind: Service
metadata:
  name: video-generator-service
  namespace: content-api
spec:
  selector:
    app: video-generator
  ports:
  - port: 8000
    targetPort: http
    name: http
  - port: 8001
    targetPort: metrics
    name: metrics
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-generator-hpa
  namespace: content-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-generator
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 